# Generated by Django 5.1.1 on 2024-10-17 09:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_name', models.CharField(max_length=50)),
                ('bussiness_email', models.EmailField(max_length=40)),
                ('bussiness_ph', models.PositiveIntegerField(blank=True, null=True)),
                ('bussiness_address', models.CharField(max_length=50)),
                ('shipping_address', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=30)),
                ('documents', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=dict, null=True, size=None)),
                ('approval_status', models.BooleanField(default='pending')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SellerDetail', to='orders.categorymaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SellerDetail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SellerRegister',
                'ordering': ['created_at'],
            },
        ),
    ]
