# Generated by Django 5.1.1 on 2024-10-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sellerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetail',
            name='approval_status',
            field=models.CharField(default='pending'),
        ),
    ]
