# Generated by Django 5.1.1 on 2024-09-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_role',
        ),
        migrations.RemoveField(
            model_name='rolemapping',
            name='roles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_role_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
