# Generated by Django 5.1.1 on 2024-09-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_last_login_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemapping',
            name='roles',
            field=models.ManyToManyField(to='users.rolemaster'),
        ),
    ]
