# Generated by Django 4.2.15 on 2024-10-08 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymentdetails',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='wallet',
        ),
        migrations.AddField(
            model_name='historicalpaymentdetails',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.wallettransaction'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='wallet_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='PaymentDetails', to='transactions.wallettransaction'),
            preserve_default=False,
        ),
    ]
