# Generated by Django 4.2.15 on 2024-10-08 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_remove_historicalpaymentdetails_wallet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpaymentdetails',
            old_name='order',
            new_name='checkout',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='order',
            new_name='checkout',
        ),
        migrations.AddField(
            model_name='historicalpaymentdetails',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='paymentdetails',
            table='PaymentDetails',
        ),
        migrations.AlterModelTable(
            name='walletdetails',
            table='WalletDetails',
        ),
        migrations.AlterModelTable(
            name='wallettransaction',
            table='WalletTransaction',
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetails', to='transactions.paymentdetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'OrderDetails',
            },
        ),
        migrations.CreateModel(
            name='HistoricalOrderDetails',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('order_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.paymentdetails')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order details',
                'verbose_name_plural': 'historical order detailss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
