# Generated by Django 4.2.15 on 2024-10-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_buyproducts_quantity_historicalbuyproducts_quantity'),
        ('transactions', '0003_rename_order_historicalpaymentdetails_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderdetails',
            name='checkout',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.buyproducts'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetails', to='orders.buyproducts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalorderdetails',
            name='order_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderDetails', to='transactions.paymentdetails'),
        ),
    ]
