# Generated by Django 4.2.15 on 2024-10-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_historicalorderdetails_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalOrderDetails',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
