# Generated by Django 4.2.15 on 2024-10-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_buyproducts_quantity_historicalbuyproducts_quantity'),
        ('transactions', '0005_remove_orderdetails_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymentdetails',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='checkout',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='checkout',
            field=models.ManyToManyField(related_name='PaymentDetails', to='orders.buyproducts'),
        ),
    ]
