# Generated by Django 4.2.15 on 2024-10-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_orderdetails_historicalorderdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='checkout',
        ),
        migrations.AlterModelTable(
            name='orderdetails',
            table='OrderDetails',
        ),
    ]
