# Generated by Django 5.1.1 on 2024-10-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_shipmentdetails_ordertracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentdetails',
            name='is_send_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpaymentdetails',
            name='to_sender_amount',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='is_send_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='to_sender_amount',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
    ]
