# Generated by Django 5.1.1 on 2024-10-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_historicalpaymentdetails_is_send_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordertracking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
