# Generated by Django 4.2.15 on 2024-10-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_comment_feedbackmaster_historicalwishlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfeedback',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
    ]
