# Generated by Django 4.2.15 on 2024-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_feedback_is_report_historicalfeedback_is_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_report',
        ),
        migrations.RemoveField(
            model_name='historicalfeedback',
            name='is_report',
        ),
        migrations.AddField(
            model_name='feedbackmaster',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfeedbackmaster',
            name='is_report',
            field=models.BooleanField(default=False),
        ),
    ]
