# Generated by Django 5.1.1 on 2024-10-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_feedback_is_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductmaster',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
