# Generated by Django 4.2.15 on 2024-10-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_feedback_is_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyproducts',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalbuyproducts',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
