# Generated by Django 5.1.1 on 2024-09-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_historicalbuyproduct_historicalcategorymaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyproduct',
            old_name='total',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='historicalbuyproduct',
            old_name='total',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='historicalcartitems',
            old_name='total_price',
            new_name='price',
        ),
    ]
