# Generated by Django 4.2.15 on 2024-10-08 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_buyproducts_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyproducts',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='historicalbuyproducts',
            name='quantity',
        ),
    ]
