# Generated by Django 5.1.1 on 2024-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_total_buyproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historicalcartitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
