# Generated by Django 5.1.1 on 2024-09-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_cartitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
