# Generated by Django 4.2.15 on 2024-10-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_buyproducts_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyproducts',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalbuyproducts',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
