# Generated by Django 4.2.15 on 2024-10-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_buyproducts_quantity_historicalbuyproducts_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfeedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
