# Generated by Django 5.1.1 on 2024-10-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_historicalproductmaster_view_count_and_more'),
        ('orders', '0008_feedback_rating_historicalfeedback_rating'),
    ]

    operations = [
    ]
