# Generated by Django 4.2.15 on 2024-10-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_historicalproductmaster_view_count_and_more'),
        ('orders', '0008_feedback_rating_historicalfeedback_rating'),
    ]

    operations = [
    ]
