# Generated by Django 5.1.1 on 2024-10-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20241009_0958'),
        ('orders', '0010_historicalproductview_productview'),
        ('orders', '0010_historicalsubcategory_subcategory_and_more'),
    ]

    operations = [
    ]
