# Generated by Django 5.1.1 on 2024-10-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_merge_20241015_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproductmaster',
            name='return_window_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='return_window_days',
            field=models.IntegerField(default=14),
        ),
    ]
